### ISSUE TITLE
Export constant from Python module

### ISSUE THREAD

**Issue by jeandrek** [BookOwl/nustack#11]
I want to export a constant variable to Nustack.
I tried this:

``` py
@module.register("AF_INET")
nu_AF_INET = socket.AF_INET
```

but it's not valid syntax.

``` py
module.AF_INET = socket.AF_INET
```

doesn't work either.

**Comment by jeandrek** [comment]
I found

``` py
module.contents["AF_INET"] = socket.AF_INET
```

works, but this might break... Is this guaranteed to work and safe to use?

**Comment by jeandrek** [comment]
```
>>> Socket::SOCK_STREAM Socket::AF_INET Socket::socket show
<socket.socket fd=3, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_DGRAM, proto=0>
>>> 
```

:smiley: 
This won't work, though.
How do I make a new type? Just make a class with get and set functions?

**Comment by BookOwl** [comment]
The way to register a constant value in a nustack extension module is to use `module.registerValue(name, val)`, where "name" is the name that will be used to access the value and "val" should be a tokenize.Token containing the value. An example can be found in the stdlib.String module.

**Comment by BookOwl** [comment]
> ```
> >> Socket::SOCK_STREAM Socket::AF_INET Socket::socket show
> <socket.socket fd=3, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_DGRAM, proto=0>
> >> 
> ```
> 
> :smiley: 
> This won't work, though.
> How do I make a new type? Just make a class with get and set functions?

The tokenize class takes care of extracting attributes from values automatically, so you _should_ just need to wrap the socket up in a token like `Token("sock_obj", sock)`. Unfortunately, it is impossible to programmatically determine the number of arguments a method of a object implemented in C takes, so you might need to create a pure python wrapper class that defines all the socket methods you want to support and just passes them on to the wrapped socket so that Nustack can determine how many arguments it takes.

**Comment by jeandrek** [comment]
> Unfortunately, it is impossible to programmatically determine the number of arguments a method of a object implemented in C takes,

This is a wrapper around `socket`. Is that implemented in C?
Edit: I think your right:

```
>>> Socket::AF_INET Socket::SOCK_STREAM Socket::socket ::connect
--ERROR--
ValueError - no signature found for builtin <built-in method connect of socket object at 0x7f0e72d14d68>
Raise error? (y/n) y
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.5/site-packages/nustack/__main__.py", line 68, in <module>
    main()
  File "/usr/lib/python3.5/site-packages/nustack/__main__.py", line 56, in main
    interp.eval(code)
  File "/usr/lib/python3.5/site-packages/nustack/interpreter.py", line 141, in eval
    self.call_external(val)
  File "/usr/lib/python3.5/site-packages/nustack/interpreter.py", line 188, in call_external
    numargs = getnumargs(val)
  File "/usr/lib/python3.5/site-packages/nustack/interpreter.py", line 12, in getnumargs
    sig = inspect.signature(func)
  File "/usr/lib/python3.5/inspect.py", line 2989, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "/usr/lib/python3.5/inspect.py", line 2739, in from_callable
    follow_wrapper_chains=follow_wrapped)
  File "/usr/lib/python3.5/inspect.py", line 2230, in _signature_from_callable
    skip_bound_arg=skip_bound_arg)
  File "/usr/lib/python3.5/inspect.py", line 2060, in _signature_from_builtin
    raise ValueError("no signature found for builtin {!r}".format(func))
ValueError: no signature found for builtin <built-in method connect of socket object at 0x7f0e72d14d68>
```

**Comment by jeandrek** [comment]
Is

``` py
module.registerValue("has_ipv6", Token("lit_bool", socket.has_ipv6))
```

right?

**Comment by jeandrek** [comment]
I have this:

``` py
# wrapper around socket.socket in Python
class NuStackSocket:
    def __init__(self, s):
        self.socket = s
        self.family = self.socket.family
        self.type = self.socket.type
        self.proto = self.socket.proto
    # ...
    def connect(self, hostname, port):
        self.socket.connect((hostname, port))
    # ...
```

But I think it's only passing one argument, because I get this error:

```
>>> 80 "www.python.org" Socket::AF_INET Socket::SOCK_STREAM Socket::socket ::connect
--ERROR--
TypeError - connect() missing 1 required positional argument: 'port'
Raise error? (y/n) y
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.5/site-packages/nustack/__main__.py", line 68, in <module>
    main()
  File "/usr/lib/python3.5/site-packages/nustack/__main__.py", line 56, in main
    interp.eval(code)
  File "/usr/lib/python3.5/site-packages/nustack/interpreter.py", line 141, in eval
    self.call_external(val)
  File "/usr/lib/python3.5/site-packages/nustack/interpreter.py", line 192, in call_external
    ret = val(*func_args)
TypeError: connect() missing 1 required positional argument: 'port'
```

**Comment by BookOwl** [comment]
Can you post your entire module so I can test it?

**Comment by jeandrek** [comment]
Here's my module so far:

``` py
#!python3
# MIT (Expat?) License
# See https://github.com/BookOwl/nustack/blob/master/LICENSE.txt
"""Socket - Berkeley-style sockets for Nustack

This is a wrapper around the Python socket module.
"""

from nustack.extensionbase import Module, Token
module = Module("Socket")

import socket

# wrapper around socket.socket in Python
class NuStackSocket:
    def __init__(self, s):
        self.socket = s
        self.family = self.socket.family
        self.type = self.socket.type
        self.proto = self.socket.proto
    def accept(self):
        return self.socket.accept()
    def bind(self, hostname, port):
        self.socket.bind((hostname, port))
    def close(self):
        self.socket.close()
    def connect(self, hostname, port):
        self.socket.connect((hostname, port))
    def connect_ex(self, address):
        return self.socket.connect_ex(address)
    def detach(self):
        return self.socket.detach()
    def dup(self):
        self.socket.dup()
    def fileno(self):
        return self.socket.fileno()
    def get_inheritable(self):
        return self.socket.get_inheritable()
    def getpeername(self):
        return self.socket.getpeername()
    def getsockopt(self, level, optname):
        return self.socket.getsockopt(level, optname)
    def gettimeout(self):
        return self.socket.gettimeout()
    def listen(self):
        return self.socket.listen()
    def recv(self, bufsize):
        return self.socket.recv(bufsize)
    def recvfrom(self, bufsize):
        return self.socket.recvfrom(bufsize)
    def sendall(self, bytes):
        return self.socket.sendall(bytes)

@module.register("socket")
def nu_socket(env):
    socket_type = env.stack.pop().val
    socket_family = env.stack.pop().val
    s = socket.socket(socket_family, socket_type)
    ns = NuStackSocket(s)
    env.stack.push(Token("sock_obj", ns))

# Socket families
def sftok(val):
    return Token("sock_family", val)

module.registerValue("AF_INET", sftok(socket.AF_INET))
module.registerValue("AF_INET6", sftok(socket.AF_INET6))

try:
    module.registerValue("AF_UNIX", sftok(socket.AF_UNIX))
except:
    pass

# Socket types
def sttok(val):
    return Token("sock_type", val)

module.registerValue("SOCK_STREAM", sttok(socket.SOCK_STREAM))
module.registerValue("SOCK_DGRAM", sttok(socket.SOCK_DGRAM))
module.registerValue("SOCK_RAW", sttok(socket.SOCK_RAW))
module.registerValue("SOCK_RDM", sttok(socket.SOCK_RDM))
module.registerValue("SOCK_SEQPACKET", sttok(socket.SOCK_SEQPACKET))

module.registerValue("has_ipv6", Token("lit_bool", socket.has_ipv6))
```

**Comment by BookOwl** [comment]
I fixed the bug. The updated code is in the v0.11-dev branch.

**Comment by BookOwl** [comment]
v0.11 fixes this.

**Comment by jeandrek** [comment]
Cool.
