### ISSUE TITLE
How to import Python module?

### ISSUE THREAD

**Issue by towerofnix** [BookOwl/nustack#4]
I have the following file structure:

```
nustack test/
  main.nu
  test_module.py
```

**main.nu**

```
`test_module import
test_module::hello show
```

**test_module.py**

``` python
from nustack.extensionbase import Module, Token

module = Module("test_module")


@module.register("hello")
def hello():
    print("Hello")
    env.stack.push(Token("string", "hello"))
```

When I run `nustack main.nu`:

```
--ERROR--
ImportError - No module named 'nustack.stdlib.test_module'
Raise error? (y/n) y
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nustack/interpreter.py", line 132, in eval
    val = self.scope.lookup(valname[0])
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nustack/interpreter.py", line 59, in lookup
    raise ScopeLookupError("%s does not exist!" % name)
nustack.interpreter.ScopeLookupError: import does not exist!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nustack/stdlib/builtins.py", line 357, in import_
    f = open(os.path.join(stddir, "/".join(namesplit)) + '.nu', "r")
FileNotFoundError: [Errno 2] No such file or directory: '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nustack/stdlib/test_module.nu'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nustack/stdlib/builtins.py", line 372, in import_
    m = importlib.import_module("nu_ext_" + name)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'nu_ext_test_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nustack/__main__.py", line 27, in <module>
    interp.run(code, file=fname)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nustack/interpreter.py", line 92, in run
    self.eval(self._code)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nustack/interpreter.py", line 136, in eval
    f(self)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nustack/stdlib/builtins.py", line 374, in import_
    m = importlib.import_module("nustack.stdlib.%s" % name)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'nustack.stdlib.test_module'
```

**Comment by BookOwl** [comment]
~~You have to name your Python module "nu_ext_"  + module_name + ".py" and put it on your module search path.~~
Please see https://github.com/BookOwl/nustack/issues/4#issuecomment-192765677

**Comment by BookOwl** [comment]
I need to document this more.

**Comment by towerofnix** [comment]
Thanks, that works!

**Comment by jeandrek** [comment]
> You have to name your Python module "nu_ext_" + module_name + ".py" and put it on your module search path.
1. What is my search path?
2. Can I modify it with an environment variable (eg `STACKPATH`)

**Comment by BookOwl** [comment]
> 1. What is my search path?
> 2. Can I modify it with an environment variable (eg STACKPATH)
1. The module search path is a list of directories Python searches when it tries to find modules and packages. You can view your search path by running the following script: `import sys; print(sys.path) # sys.path is the module search path`
2. You can adjust the search path by setting the `PYTHONPATH` environment variable to a list of semicolon (`;`) separated paths. For example, if I set PYTHONPATH to `C:\\my_python_code;C:\\my_libs`, and I try to import the module `spam`, Python would look in C:\my_python_code and C:\my_libs, along with some other places like the scripts directory and the location of the standard library.

However, I should note that the prefered way to name extensions is to create a package named nu_ext and put your module in file named your_mod.py in that package, where your_mod is the name of your module. Python 3.3+ namespace packages may help here.

**Comment by BookOwl** [comment]
Any other questions?

**Comment by jeandrek** [comment]
I know what a search path is, I was asking what my Nustack search path is set to :stuck_out_tongue: So I just use my normal Python search path?
Btw on *nix then PYTHONPATH is seperated by colons (`:`) instead of semicolons.
No, I don't have any other questions.

**Comment by BookOwl** [comment]
OK, I thought that you were asking about the Python search path. Yes, for extension modules Nustack just piggybacks off of the Python search path. For normal modules, Nustack just uses a path that is relative from the scripts home dir, although I plan on extending it soon to look in other places.
